/**
 * Business rule violation. Maps to HTTP 4xx by the presentation layer.
 */
export class DomainError extends Error {
  constructor(
    public readonly code: string,
    message?: string,
    public readonly details?: Record<string, unknown>,
  ) {
    super(message ?? code);
    this.name = 'DomainError';
  }
}

/**
 * System / unexpected error. Maps to HTTP 5xx.
 */
export class AppError extends Error {
  constructor(
    public readonly code: string,
    message?: string,
    public readonly cause?: unknown,
  ) {
    super(message ?? code);
    this.name = 'AppError';
  }
}

// Known domain error codes used across modules (keep in sync with docs/design)
export const ErrorCodes = {
  // identity
  INVALID_CREDENTIAL: 'INVALID_CREDENTIAL',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  UNDER_AGE: 'UNDER_AGE',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  /** T-082 Phase D — HIBP / 자체 blocklist 둘 다 사용 가능. NIST §5.1.1.2. */
  BREACHED_PASSWORD: 'BREACHED_PASSWORD',
  /** T-082 Phase D — N회 실패 후 잠금. NIST §5.2.2. */
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  // catalog
  IDOL_NOT_FOUND: 'IDOL_NOT_FOUND',
  AGENCY_NOT_FOUND: 'AGENCY_NOT_FOUND',
  AGENCY_HAS_IDOLS: 'AGENCY_HAS_IDOLS',
  // fandom
  FAN_CLUB_NOT_FOUND: 'FAN_CLUB_NOT_FOUND',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  PAID_FAN_CLUB_NOT_SUPPORTED: 'PAID_FAN_CLUB_NOT_SUPPORTED',
  // chat
  NO_COUPON: 'NO_COUPON',
  CHAT_ROOM_NOT_FOUND: 'CHAT_ROOM_NOT_FOUND',
  CHAT_GATE_NOT_MEMBER: 'CHAT_GATE_NOT_MEMBER',
  CHAT_MESSAGE_TOO_LONG: 'CHAT_MESSAGE_TOO_LONG',
  AUTO_MESSAGE_NOT_FOUND: 'AUTO_MESSAGE_NOT_FOUND',
  AUTO_MESSAGE_PAST_SCHEDULE: 'AUTO_MESSAGE_PAST_SCHEDULE',
  AUTO_MESSAGE_ALREADY_DISPATCHED: 'AUTO_MESSAGE_ALREADY_DISPATCHED',
  // commerce
  DUPLICATE_RECEIPT: 'DUPLICATE_RECEIPT',
  // audition
  NOT_ENOUGH_TICKETS: 'NOT_ENOUGH_TICKETS',
  ROUND_CLOSED: 'ROUND_CLOSED',
  AUDITION_NOT_FOUND: 'AUDITION_NOT_FOUND',
  ROUND_NOT_FOUND: 'ROUND_NOT_FOUND',
  AUDITION_ENTRY_NOT_FOUND: 'AUDITION_ENTRY_NOT_FOUND',
  AUDITION_INVALID_TRANSITION: 'AUDITION_INVALID_TRANSITION',
  ROUND_INVALID_TRANSITION: 'ROUND_INVALID_TRANSITION',
  AUDITION_MUST_BE_DRAFT: 'AUDITION_MUST_BE_DRAFT',
  AUDITION_NOT_ACTIVE: 'AUDITION_NOT_ACTIVE',
  AUDITION_INVALID_DATE_RANGE: 'AUDITION_INVALID_DATE_RANGE',
  IDOL_ALREADY_IN_AUDITION: 'IDOL_ALREADY_IN_AUDITION',
  VOTE_RULE_NOT_FOUND: 'VOTE_RULE_NOT_FOUND',
  VOTE_RULE_INVALID_WEIGHTS: 'VOTE_RULE_INVALID_WEIGHTS',
  VOTE_ROUND_NOT_ACTIVE: 'VOTE_ROUND_NOT_ACTIVE',
  VOTE_DAILY_LIMIT_EXCEEDED: 'VOTE_DAILY_LIMIT_EXCEEDED',
  VOTE_METHOD_NOT_ALLOWED: 'VOTE_METHOD_NOT_ALLOWED',
  IDOL_NOT_IN_AUDITION: 'IDOL_NOT_IN_AUDITION',
  IDOL_ELIMINATED: 'IDOL_ELIMINATED',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_INACTIVE: 'PRODUCT_INACTIVE',
  PRODUCT_SKU_TAKEN: 'PRODUCT_SKU_TAKEN',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  PROVIDER_NOT_SUPPORTED: 'PROVIDER_NOT_SUPPORTED',
  INVALID_DELIVERY_PAYLOAD: 'INVALID_DELIVERY_PAYLOAD',
  INVALID_RECEIPT: 'INVALID_RECEIPT',
  // photocard
  PHOTOCARD_SET_NOT_FOUND: 'PHOTOCARD_SET_NOT_FOUND',
  PHOTOCARD_SET_EMPTY: 'PHOTOCARD_SET_EMPTY',
  // admin-ops (FR-102)
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  ADMIN_EMAIL_DUPLICATE: 'ADMIN_EMAIL_DUPLICATE',
  ADMIN_LIMIT_EXCEEDED: 'ADMIN_LIMIT_EXCEEDED',
  ADMIN_SELF_MODIFICATION_FORBIDDEN: 'ADMIN_SELF_MODIFICATION_FORBIDDEN',
  ADMIN_LAST_ADMIN_DEMOTION: 'ADMIN_LAST_ADMIN_DEMOTION',
  // issue-tracker (FR-103)
  ISSUE_INVALID_DATE_RANGE: 'ISSUE_INVALID_DATE_RANGE',
  // media (FR-103-D)
  ATTACHMENT_NOT_FOUND: 'ATTACHMENT_NOT_FOUND',
  ATTACHMENT_TOO_LARGE: 'ATTACHMENT_TOO_LARGE',
  ATTACHMENT_MIME_NOT_ALLOWED: 'ATTACHMENT_MIME_NOT_ALLOWED',
  // project-notes (FR-104)
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  NOTE_FORBIDDEN: 'NOTE_FORBIDDEN',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
